<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxwORRb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxwORRb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxwORRb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxwORRb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGxwORRb\App_KernelDevDebugContainer([
    'container.build_hash' => 'GxwORRb',
    'container.build_id' => 'aa930b9d',
    'container.build_time' => 1603658938,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxwORRb');
